// Test-only bindings, supplied by vitest.config.ts. Neither is in wrangler.jsonc, so
// neither exists on a deployment — they are declared here rather than generated by
// `wrangler types`.
declare namespace Cloudflare {
  interface Env {
    /** The real migrations, read from ./migrations at startup and applied per file. */
    TEST_MIGRATIONS: import('cloudflare:test').D1Migration[]
    /**
     * A second D1 database that is deliberately never migrated.
     *
     * It is the state Cloudflare's deploy button leaves behind — a database that
     * exists and answers `select 1` with no Charcha schema in it — and there is no
     * other honest way to reach it: test/worker/apply-migrations.ts migrates `DB`
     * before any test in the file runs, and dropping tables out of it would leave the
     * rest of the suite running against a schema nobody declared.
     * Used by test/worker/db/database-status.test.ts.
     */
    TEST_EMPTY_DB: D1Database
  }
}
